
<div data-role="header">
		<h1>Contact details</h1>
	
		<a  href="#" style="text-decoration: none" id="save-edit-contact-button" data-role="button" data-icon="check" class="ui-btn-right jqm-save">Save</a>
<a href="#menu" style="text-decoration: none" id="back-edit-contact-button" data-rel="back" data-role="button" data-inline="true" data-icon="back" class="ui-btn-left">Back to pervious page</a>
	</div><!-- /header -->

	<div data-role="content" id="contact-details-content">
		<div id="edit-contact">
		   
		   
	    </div>
 
	</div><!-- /content -->


<?php 
$id =  $_SESSION['id'];
$params = array ('version' =>'3',
                 'contact_id' => $id
                 );
$results = civicrm_api("contact","get",$params );

?>

<script>
var contactId = <?php echo $id; ?>;
var contact = <?php echo json_encode($results); ?>;
contact = contact.values[contactId];
var paramIds = {};
var jsonProfile = {};
$( function(){
    	createContactEditfields();

	$('#save-edit-contact-button').click(function(){ updateContact(contactId); });
});


function createContactEditfields(){
  //this function gets all of the available contact fields in the profile
  
  //get the profile fields
  var dataUrl = '<?php echo "{$path}/profile/edit?gid={$new_individual_profile_id}&reset=1&id={$id}&json=1"; ?>';  
  $.getJSON( dataUrl,
  {
    format: "json"
  },
  function(data) {
    jsonProfile = data;
   
    $().crmAPI ('UFField','get',{'version' :'3', 'uf_group_id' : 1}

    ,{ 
      ajaxURL: crmajaxURL,
      success:function (data){
                 
                    $.each(data.values, function(index, value) {
        //Logic to handle the difference between the field names generated by the API and JSON object, specifically with phone, email and address fields. 
        if (value.location_type_id){
          if (value.field_name.indexOf("phone") != -1){
            var field = jsonProfile[value.field_name+"-"+value.location_type_id+"-"+value.phone_type_id];
          }
          else{
            var field = jsonProfile[value.field_name+"-"+value.location_type_id];
          }
        }
        else if (value.field_name.indexOf("email") != -1){
          var field = jsonProfile[value.field_name+"-Primary"];
        }
        else if (value.field_name.indexOf("phone") != -1){
          var field = jsonProfile[value.field_name+"-Primary-"+value.phone_type_id];
        }
        else{
          var field = jsonProfile[value.field_name];
        }
        field = field.html;
        //build all fields from profile
        $('#edit-contact').append('<div data-role="fieldcontain" class="ui-field-contain ui-body ui-br">'+field+'</div>');
        var eid = $(field).attr('id');
        paramIds[eid]= "";
        console.log(paramIds[eid]);
        $('#'+eid).val(contact[value.field_name]);
        
        var tagName = $(field).get(0).tagName;
        //refresh the display after adding inputs and selects
        if (tagName == 'INPUT'){
          $('#'+eid).textinput();
          $('#'+eid).attr( 'placeholder', value.label )
        }
        if (tagName == 'SELECT'){
          $('#'+eid).selectmenu();
          $('#'+eid).parent().parent().prepend('<label for="'+eid+'">'+value.label+':</label>');
        }
      });


    }
  });
 
});
}


function updateContact(contactId) {

$.each(paramIds, function(index, value) {
         
         paramIds[index] = $('#'+index).val();
         
   });


/*console.log(paramIds,'ds');*/

  paramIds.version = "3";
  paramIds.contact_type = "Individual";
  paramIds.contact_id = contactId;
  paramIds.profile_id = newIndividualProfileId;
 
 $().crmAPI ('Profile','set', paramIds
  ,{ 
             ajaxURL: crmajaxURL,
                 success:function (data){
                 $.each(data.values, function(key, value) {           
            
                $.mobile.changePage("<?php print url('civicrm/mobile/contact/') ?>"+value.id);
                                     });
   
  }
  });
}




</script>
