

<div id="jqm-add-header" data-role="header">
   <h3>Name and Address</h3>
   <a href="#contact-search" style="text-decoration: none" id="back-add-contact-button" data-role="button" data-icon="delete" class="ui-btn-left jqm-home">Cancel</a>
   <a href="#" style="text-decoration: none" id="save-add-contact-button" data-role="button" data-ajax="false" data-icon="check" class="ui-btn-right jqm-home" onclick="createContact()">Save</a>



 <a href="#" style="display:none" style="text-decoration: none" id="save-edit-contact-button" data-role="button" data-icon="check" class="ui-btn-right jqm-save" >Save</a>
 <a href="#menu"  style="display:none" style="text-decoration: none" id="back-edit-contact-button" data-rel="back" data-role="button" data-inline="true" data-icon="back" class="ui-btn-left">Back to pervious page</a>


</div> <!--End of header-->


<div data-role="fieldcontain" id="contact-details-content">

 <div id="edit-contact">
 </div>
</div><!-- /content -->


<div data-role="fieldcontain" id="add-contact-content">
 <div id="add_contact" style="display:none"></div>
</div>
  </div>
<?php 

if(isset($_SESSION['id'])) {
  $cid =  $_SESSION['id'];
  }
$params = array ('version' =>'3',
                 'contact_id' => $cid
                 );
$results = civicrm_api("contact","get",$params );

?>
<?php 
  $new_individual_profile_id = 1; 
  $profile_title=civicrm_api("UFGroup","get", array ('version' =>'3', 'id' =>$new_individual_profile_id));
  $profile_title=$profile_title['values'][$new_individual_profile_id]['title'];
  $path=$_SERVER['REQUEST_URI'] ;
  $path=dirname($path);
?>

<script>
var profileTitle = "<?php echo $profile_title; ?>";
var newIndividualProfileId = 1;
var params = {};
var jsonaddProfile = {};
var fieldIds = {};
var count=0;
$(function() {

  $("#add-contact-button").click(function() {
    addContact();
    var dataUrl = '<?php echo "{$path}/profile/create?gid={$new_individual_profile_id}&reset=1&json=1"; ?>';

    $.getJSON( dataUrl, { format: "json" },
      function(data) {
        jsonaddProfile = data;
        $().crmAPI ('UFField','get',{'version' :'3', 'uf_group_id' : 1} ,
            { ajaxURL: crmajaxURL,
              success: function (data){
              $.each(data.values, function(index, value) {
                  //Logic to handle the difference between the field names generated by the API and JSON object, specifically with phone, email and address fields. 
                if (value.location_type_id){
                  if (value.field_name.indexOf("phone") != -1){
                    var field = jsonaddProfile[value.field_name+"-"+value.location_type_id+"-"+value.phone_type_id];
                  }
                  else{
                    var field = jsonaddProfile[value.field_name+"-"+value.location_type_id];
                  }
                }
                else if (value.field_name.indexOf("email") != -1){
                  var field = jsonaddProfile[value.field_name+"-Primary"];
                }
                else if (value.field_name.indexOf("phone") != -1){
                  var field = jsonaddProfile[value.field_name+"-Primary-"+value.phone_type_id];
                }
                else{
                  var field = jsonaddProfile[value.field_name];
                }
                var field = field.html;
                //build all fields from profile
                $('#add_contact').append('<div data-role="fieldcontain" class="ui-field-contain ui-body ui-br">'+field+'</div>');
                var id = $(field).attr('id');
                fieldIds[id]= id;
                var tagName = $(field).get(0).tagName;
                //refresh the display after adding inputs and selects
                if (tagName == 'INPUT'){
                  $('#'+id).textinput();
                  $('#'+id).attr( 'placeholder', value.label )
                }
                if (tagName == 'SELECT'){
                  $('#'+id).selectmenu();
                  $('#'+id).parent().parent().prepend('<label for="'+id+'">'+value.label+':</label>');
                }
                count=count+1;
              });
            }
        });
      });
  });
$("#back-add-contact-button").click(function() {
$("div").each(function(count) {
    $("#add_contact div:first-child").remove(); 
});

});

$("#back-edit-contact-button").click(function() {
$("div").each(function(count) {
    $("#edit-contact div:first-child").remove(); 
});

});


});


function addContact() {
  /*$('#add-contact-content').append($('#add_contact'));*/
  $('#jqm-add-header .ui-title').text(profileTitle);
  $('#save-add-contact-button').show();
  $('#add_contact').show();
  $('#save-edit-contact-button').hide();
  $('#back-edit-contact-button').hide();
}

function editContact(){
  $('#jqm-add-header .ui-title').text("Edit Contact");
	createContactEditfields();
  //  $.get("civimobile.contacts.tpl.php");
  $('#add_contact').hide();
	$('#back-edit-contact-button').show();
  $('#save-edit-contact-button').show();
  $('#back-add-contact-button').hide(); 
  $('#save-add-contact-button').hide();
  $('#save-edit-contact-button').click(function(){ updateContact(contactId); });
  
}


function createContact() {
  $.each(fieldIds, function(index, value) {
    fieldIds[index] = $('#'+index).val();
  });	

  fieldIds.version = "3";
  fieldIds.contact_type = "Individual";
  fieldIds.profile_id = newIndividualProfileId;
  $().crmAPI ('Contact','create', fieldIds
    ,{ 
      ajaxURL: crmajaxURL,
        success:function (data){
          $.each(data.values, function(key, value) { 
            fieldIds.contact_id = value.id;
            //console.log(fieldIds);
            con_id=value.id;

            $().crmAPI ('Profile','set', fieldIds
              ,{ 
                ajaxURL: crmajaxURL,
                  success:function (data){    
                    $.each(data.values, function(key, value) { 
                      $.mobile.changePage("<?php print url('civicrm/mobile/contact/') ?>"+value.id);
                    });
                  } 
              });
          });
        }
    });
}





var contactId = <?php echo $cid; ?>;
var contact = <?php echo json_encode($results); ?>;
contact = contact.values[contactId];
var paramIds = {};
var jsonProfile = {};

function createContactEditfields(){
  //this function gets all of the available contact fields in the profile

  //get the profile fields
  var dataUrl = '<?php echo "{$path}/profile/edit?gid={$new_individual_profile_id}&reset=1&id={$id}&json=1"; ?>';  
  $.getJSON( dataUrl,
  {
    format: "json"
  },
  function(data) {
    jsonProfile = data;
   
    $().crmAPI ('UFField','get',{'version' :'3', 'uf_group_id' : 1}

    ,{ 
      ajaxURL: crmajaxURL,
      success:function (data){
                 
                    $.each(data.values, function(index, value) {
        //Logic to handle the difference between the field names generated by the API and JSON object, specifically with phone, email and address fields. 
        if (value.location_type_id){
          if (value.field_name.indexOf("phone") != -1){
            var field = jsonProfile[value.field_name+"-"+value.location_type_id+"-"+value.phone_type_id];
          }
          else{
            var field = jsonProfile[value.field_name+"-"+value.location_type_id];
          }
        }
        else if (value.field_name.indexOf("email") != -1){
          var field = jsonProfile[value.field_name+"-Primary"];
        }
        else if (value.field_name.indexOf("phone") != -1){
          var field = jsonProfile[value.field_name+"-Primary-"+value.phone_type_id];
        }
        else{
          var field = jsonProfile[value.field_name];
        }
        field = field.html;
        //build all fields from profile
        $('#edit-contact').append('<div data-role="fieldcontain" class="ui-field-contain ui-body ui-br">'+field+'</div>');
        var eid = $(field).attr('id');
        paramIds[eid]= "";
        
        $('#'+eid).val(contact[value.field_name]);
        
        var tagName = $(field).get(0).tagName;
        //refresh the display after adding inputs and selects
        if (tagName == 'INPUT'){
          $('#'+eid).textinput();
          $('#'+eid).attr( 'placeholder', value.label )
        }
        if (tagName == 'SELECT'){
          $('#'+eid).selectmenu();
          $('#'+eid).parent().parent().prepend('<label for="'+eid+'">'+value.label+':</label>');
        }
       
      });
    }
  });
});
}


function updateContact(contactId) {

$.each(paramIds, function(index, value) {
         
         paramIds[index] = $('#'+index).val();
         
   });

  paramIds.version = "3";
  paramIds.contact_type = "Individual";
  paramIds.contact_id = contactId;
  paramIds.profile_id = newIndividualProfileId;
 
 $().crmAPI ('Profile','set', paramIds
  ,{ 
             ajaxURL: crmajaxURL,
                 success:function (data){
                 $.each(data.values, function(key, value) {           
            
                $.mobile.changePage("<?php print url('civicrm/mobile/contact/') ?>"+value.id);
                                     });
   
  }
  });
}


</script>

<?php require_once 'civimobile.footer.php'; ?>






